
services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_BIND_ADDRESS: 0.0.0.0
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  backend:
    build: .
    volumes:
      - ./photos:/app/photos
    container_name: python-backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DB=mydatabase
    command: ["./wait-for-it.sh", "db:3306", "--timeout=60", "--", "python", "app.py"]


volumes:
  app-network:
    driver: bridge
  mysql-data:

